### ISSUE TITLE
Where i can set payumoney salt and merchant id?

### ISSUE THREAD

**Issue by abhishekjain-itsme** [tzsk/payu#19]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
* Laravel 5.5
* Version used (e.g. PHP 7, HHVM 3):
* Operating system and version (Windows 10):
* Link to your project:
* ...
* ...
Where i can set my merchant id and salt? There is no information regarding this.

**Comment by tzsk** [comment]
@abhishekjain-itsme PayuMoney is not currently supported in any release. It is currently in development in `dev-master` branch. And there are a lot of features coming in `Version 2.0` Ex. Support for Multi Account Payment & PayuMoney Support. 

There is a problem with Payment Verification from PayuMoney side. I am currently coordinating with PayuMoney team to fix their Verification API. 

And the documentation is also not done for `V2.0` it is currently underway.

To answer your question. After you run `vendor:publish` you will have `config/payu.php`. That's where the configuration goes. This is clearly mentioned in the Documentation to PUBLISH the Config file.

But as I said, even if you manage to configure your `key` and `salt` you won't be able to use this package because it currently does not support PayuMoney. But there is a workaround. Refer to issue number #16

**Comment by tzsk** [comment]
Please see Release `Version 2.0`.

PayuMoney Support Added
